config/routes.rb
CctvProject::Application.routes.draw do
  devise_for :users

  resources :channels
  resources :locations
  resources :favorites
  resources :users


  get   '/channel_pub/:id',       to: 'home#channel',  as: 'channel_pub'
  get   '/favorite',              to: 'home#favorite', as: 'my_favorite'

  post  '/up',          to: 'favorites#up',   as: 'up'
  match  '/down',       to: 'favorites#down', as: 'down', via: [:get, :post]
  root :to => 'home#dashboard'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.roles == "admin"
         can :manage, :all
       elsif user.roles == "guest"
         can :update, User, :id => user.id
         can :show, User, :id => user.id
       end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  attr_accessible :conn_type, :ip_address, :location_id, :name, :port, :status, :streaming_url, :streaming_type

  belongs_to :location

  validates_presence_of :ip_address, :location_id, :name, :port

  has_many :favorites
  has_many :users, through: :favorites

  def self.asc_name(current_page)
  	order("name")
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  attr_accessible :channel_id, :status, :user_id

  belongs_to :user
  belongs_to :channel
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name

  has_many :channels

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :mobile_phone, :phone

  belongs_to :profileable, polymorphic: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :profile_attributes, :roles
  # attr_accessible :title, :body
  has_one :profile,  as: :profileable, dependent: :destroy
  accepts_nested_attributes_for :profile

  has_many :favorites
  has_many :channels, through: :favorites

  # validates :password, presence: false
  # validates :password_confirmation, presence: false

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!, :global

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  private
  def global
	  @loc_pub = Location.order("name")
	end

end

app/controllers/channels_controller.rb
class ChannelsController < InheritedResources::Base
	load_and_authorize_resource
	
  def index
  	@channels = Channel.order('name ASC').page(params[:page]).per(10)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < InheritedResources::Base

  def up
  	fav = current_user.favorites.new(channel_id: params[:favorite][:channel_id], status: 'Favorite')
  	fav.save
  	redirect_to my_favorite_path, :notice => "You just set favorite CCTV" 
  end

  def down
  	current_user.favorites.where(channel_id: params[:favorite][:channel_id]).first.destroy

  	redirect_to my_favorite_path, :notice => "You just removed favorite CCTV" 
  end

end

app/controllers/home_controller.rb
class HomeController < InheritedResources::Base

	def dashboard
		@channel_all = Channel.asc_name(params[:page])
	end

	def channel
		@channel_pub = Channel.where("location_id =?", params[:id])
		@loc_name = Location.find(params[:id])
	end

	def favorite
		 @favorite = current_user.favorites.where(user_id: current_user.id, status: 'Favorite')
	   @favorite_count = current_user.favorites.where(user_id: current_user.id, status: 'Favorite').count
	end

end

app/controllers/locations_controller.rb
class LocationsController < InheritedResources::Base
	load_and_authorize_resource
	
  def index
  	@locations = Location.order("name")
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  load_and_authorize_resource
	before_filter :auth, only: :update

  def index
  	@users = User.where("id != ?", current_user.id).order("id DESC").page(params[:page]).per(10)
  end

  def auth
  	if params[:user] && params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/channels/_form.html.erb
<%= form_for(@channel) do |f| %>
  <% if @channel.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-block alert-danger fade in ">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Warning!</strong> <%= pluralize(@channel.errors.count, "error") %>
        <% @channel.errors.full_messages.each do |msg| %>
        <diV>
          <%= msg %>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="col-lg-6">
    <div class="input-group">
      <div>IP Address</div>
      <%= f.text_field :ip_address, class: "form-control", placeholder:"Ip Address" %>
    </div>
    <div class="input-group">
      <div>Location </div>
      <%= f.select(:location_id, options_from_collection_for_select(Location.order("name"), :id, :name, (@channel ? @channel.location_id : '')), {prompt: 'Select Location'}, {class: "form-control"}) %>
    </div>
    <div class="input-group">
      <div>Streaming URL</div>
      <%= f.text_field :streaming_url, class: "form-control", placeholder:"URL" %>
    </div>
    <div class="input-group">
      <div>Streaming Type</div>
      <%= f.select(:streaming_type, options_for_select(['Motion Jpeg', 'Video']), {prompt: 'Select Type'}, {class: "form-control"}) %>
    </div>
    <div class="input-group">
      <div>Chanell Name</div>
      <%= f.text_field :name, class: "form-control", placeholder:"Chanell Name" %>
    </div>
    <div class="input-group">
      <div>Status</div>
      <%= f.text_field :status, class: "form-control", placeholder:"Status" %>
    </div>
    <div class="input-group">
      <div>Port</div>
      <%= f.text_field :port, class: "form-control", placeholder:"Port" %>
    </div>
    <div class="input-group">
      <div>Conn Type</div>
      <%= f.select(:conn_type, options_for_select(['http', 'rtmp']), {prompt: 'Conn Type'}, {class: "form-control"}) %>
    </div>
    <div class="block"></div>
    <button type="button" class="btn btn-default">
      <%= link_to "Close", channels_path %>
    </button>
    <button type="submit" class="btn btn-primary">Save As</button>
  </div>
  <div class="block"></div>
<% end %>

app/views/channels/edit.html.erb
<div class="row">    
  <div class="bs-example">
    <div class="panel-heading">Change Channel</div><br>
    <%= render 'form' %>
  </div>
</div>

app/views/channels/index.html.erb
<div class="row">   
  <div class="bs-example">
    <div class="panel-heading">List Channels</div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Channel Name</th>
          <th>Location Channel</th>
          <th>Ip Address</th>
          <th>Port</th>
          <th width="15%">Action</th>
        </tr>
      </thead>
      <tbody>
      <% @channels.each do |channel| %>
        <tr>
          <td></td>
          <td><%= link_to channel.name, channel %></td>
          <td><%= channel.location.name %></td>
          <td><%= channel.ip_address %></td>
          <td><%= channel.port %></td>
          <td>
            <%= link_to "<span class='glyphicon glyphicon-wrench'>".html_safe, edit_channel_path(channel) %> 
            <%= link_to "<span class='glyphicon glyphicon-trash'>".html_safe, channel, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%= link_to "<span class='glyphicon glyphicon-eye-open'>".html_safe, channel %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div>
      <%= paginate @channels %>
    </div>
  </div>
</div>

app/views/channels/new.html.erb
<div class="row">    
  <div class="bs-example">
    <div class="panel-heading">Create Channel</div><br>
    <%= render 'form' %>
  </div>
</div>

app/views/channels/show.html.erb
<div class="row">
	<div class="bs-example">
		<% if notice.present? %>
			<div class="alert alert-warning fade in">
		    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
		    <%= notice %>
		  </div>
	  <% end %>
		<table class="table table-striped">
      <thead>
        <tr>
          <th width="20%">Channel Name</th>
          <th><%= @channel.name %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><b>IP Address</b></td>
          <td><%= @channel.ip_address %></td>
        </tr>
        <tr>
          <td><b>Location</b></td>
          <td><%= @channel.location.name %></td>
        </tr>
        <tr>
          <td><b>Status</b></td>
          <td><%= @channel.status %></td>
        </tr>
        <tr>
          <td><b>Port</b></td>
          <td><%= @channel.port %></td>
        </tr>
        <tr>
          <td><b>Conn Type</b></td>
          <td><%= @channel.conn_type %></td>
        </tr>
      </tbody>
    </table>

		<%= link_to 'Edit', edit_channel_path(@channel) %> |
		<%= link_to 'Back', channels_path %>
	</div>
</div>

app/views/home/channel.html.erb
<% if current_user.roles == 'guest' %>
  <div class="row">
    <ul id="myTab" class="nav nav-tabs">
      <li class="active">
        <a href="#live" data-toggle="tab">
        <%= @loc_name.name %>
        </a>
      </li>
    </ul>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade active in" id="live"> 
        <% @channel_pub.each do |channel| %>
          <div class="col-6 col-sm-6 col-lg-4 padding-bottom">
            <h4>
              <%= channel.name %>
              <% if channel.user_ids.include?(current_user.id) %>
                <%= form_for(:favorite, url: down_path, html: {class: "form_up"}, method: "post") do |f| %>
                  <%= f.hidden_field :channel_id, value: channel.id  %>
                  <button type="submit" class="glyphicon glyphicon-star-empty up"></button>
                <% end %>
              <% elsif %>
                <%= form_for(:favorite, url: up_path, html: {class: "form_up"}, method: "post") do |f| %>
                  <%= f.hidden_field :channel_id, value: channel.id %>
                  <button type="submit" class="glyphicon glyphicon-star-empty none"></button>
                <% end %>
              <% end %>
            </h4>
            <a href="<%= channel.streaming_url %>" class="swipebox" title="<%= channel.name %>">
              <img src="<%= channel.streaming_url %>" width="100%">
            </a>
          </div>
        <% end %>
    </div>
  </div>
<% end %>

app/views/home/dashboard.html.erb
<% if current_user.roles == 'admin' %>
<div class="row">
  <div class="alert alert-warning fade in">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <strong>Welcome To!</strong> Control Panel CCTV Admnistrator.
  </div>
</div>
<% end %>

<% if current_user.roles == 'guest' %>
  <div class="row">
    <ul id="myTab" class="nav nav-tabs">
      <li class="active"><a href="#live" data-toggle="tab">Channels Live CCTV</a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade active in" id="live"> 
        <% @channel_all.each do |channel| %>
          <div class="col-6 col-sm-6 col-lg-4 padding-bottom">
            <h4>
              <%= channel.name %>
              <% if channel.user_ids.include?(current_user.id) %>
                <%= form_for(:favorite, url: down_path, html: {class: "form_up"}, method: "post") do |f| %>
                  <%= f.hidden_field :channel_id, value: channel.id  %>
                  <button type="submit" class="glyphicon glyphicon-star-empty up"></button>
                <% end %>
              <% elsif %>
                <%= form_for(:favorite, url: up_path, html: {class: "form_up"}, method: "post") do |f| %>
                  <%= f.hidden_field :channel_id, value: channel.id %>
                  <button type="submit" class="glyphicon glyphicon-star-empty none"></button>
                <% end %>
              <% end %>
            </h4>
            <a href="<%= channel.streaming_url %>" class="swipebox" title="<%= channel.name %>">
              <img src="<%= channel.streaming_url %>" width="100%">
            </a>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/home/dashboard.html_tab.erb
<% if current_user.roles == 'admin' %>
<div class="row">
  <div class="alert alert-warning fade in">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <strong>Welcome To!</strong> Control Panel CCTV Admnistrator.
  </div>
</div>
<% end %>

<% if current_user.roles == 'guest' %>
  <div class="row">
    <ul id="myTab" class="nav nav-tabs">
      <li class="active"><a href="#live" data-toggle="tab">Live View</a></li>
      <li class=""><a href="#play" data-toggle="tab">Playback</a></li>
    </ul>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade active in" id="live"> 
        <% @channel_all.each do |channel| %>
          <div class="col-6 col-sm-6 col-lg-4 padding-bottom">
            <h4>
              <%= channel.name %>
              <% if channel.user_ids.include?(current_user.id) %>
                <%= form_for(:favorite, url: down_path, html: {class: "form_up"}, method: "put") do |f| %>
                  <%= f.hidden_field :channel_id, value: channel.id  %>
                  <button type="submit" class="glyphicon glyphicon-star-empty up"></button>
                <% end %>
              <% elsif %>
                <%= form_for(:favorite, url: up_path, html: {class: "form_up"}, method: "post") do |f| %>
                  <%= f.hidden_field :channel_id, value: channel.id %>
                  <button type="submit" class="glyphicon glyphicon-star-empty none"></button>
                <% end %>
              <% end %>
            </h4>
            <video id="movie" width="260" height="200" preload autoplay>
              <source src="rtmp://fl2.sz.xlcdn.com:80/sz=Deltion_College=lb1"  type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"'>
            </video>
          </div>
        <% end %>
      </div>
      <div class="tab-pane fade" id="play">
        <% @channel_all.each do |channel| %>
          <div class="col-6 col-sm-6 col-lg-4 padding-bottom">
            <h4><%= channel.name %></h4>
            <video id="movie"  width="100%" preload autoplay>
              <source src="rtmp://fl2.sz.xlcdn.com:80/sz=Deltion_College=lb1"  type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"'>
            </video>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/home/favorite.html.erb
<% if current_user.roles == 'guest' %>
  <div class="row">
    <ul id="myTab" class="nav nav-tabs">
      <li class="active">
        <a href="#live" data-toggle="tab">
        <span class='badge pull-right'>
          <%= @favorite_count %>
        </span>
          Favorite Channel
        </a>
      </li>
    </ul>
    <div id="myTabContent" class="tab-content">
      <div class="tab-pane fade active in" id="live"> 
        <% @favorite.each do |favorite| %>
          <% channel_favorites = Channel.where("id =?", favorite.channel_id).first %>
          <div class="col-6 col-sm-6 col-lg-4 padding-bottom">
            <h4>
              <%= channel_favorites.name %>
              <% if channel_favorites.user_ids.include?(current_user.id) %>
                <%= form_for(:favorite, url: down_path, html: {class: "form_up"}, method: "post") do |f| %>
                  <%= f.hidden_field :channel_id, value: channel_favorites.id  %>
                  <button type="submit" class="glyphicon glyphicon-star-empty up"></button>
                <% end %>
              <% elsif %>
                <%= form_for(:favorite, url: up_path, html: {class: "form_up"}, method: "post") do |f| %>
                  <%= f.hidden_field :channel_id, value: channel_favorites.id %>
                  <button type="submit" class="glyphicon glyphicon-star-empty none"></button>
                <% end %>
              <% end %>
            </h4>
             <a href="<%= channel_favorites.streaming_url %>" class="swipebox" title="<%= channel_favorites.name %>">
              <img src="<%= channel_favorites.streaming_url %>" width="100%">
            </a>
          </div>
        <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cctv</title>
  <%= favicon_link_tag 'icon.gif' %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>

<%= javascript_include_tag "application" %>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %> 
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-block alert-danger fade in ">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Warning!</strong> <%= pluralize(@location.errors.count, "error") %>
        <% @location.errors.full_messages.each do |msg| %>
        <diV>
          <%= msg %>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="col-lg-6">
    <div class="input-group">
      <label>Location Name</label>
      <%= f.text_field :name, class: "form-control", placeholder:"Location Name" %>
    </div>
    <button type="button" class="btn btn-default">
      <%= link_to "Close", locations_path %>
    </button>
    <button type="submit" class="btn btn-primary">Save As</button>
  </div>
  <div class="block"></div>
<% end %>

app/views/locations/index.html.erb
<div class="row">   
  <div class="bs-example">
    <div class="panel-heading">List Locations</div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th width="4%">#</th>
          <th>Location Name</th>
          <th width="15%">Action</th>
        </tr>
      </thead>
      <tbody>
      <% @locations.each do |location| %>
        <tr>
          <td></td>
          <td><%= link_to location.name, location %></td>
          <td>
            <%= link_to "<span class='glyphicon glyphicon-wrench'>".html_safe, edit_location_path(location) %> 
            <%= link_to "<span class='glyphicon glyphicon-trash'>".html_safe, location, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%= link_to "<span class='glyphicon glyphicon-eye-open'>".html_safe, location %>
          </td>
        </tr>
      <% end %>

      </tbody>
    </table>
  </div>
</div>

app/views/locations/show.html.erb
<div class="row">
	<div class="bs-example">
		<% if notice.present? %>
			<div class="alert alert-warning fade in">
		    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
		    <%= notice %>
		  </div>
	  <% end %>

		<p>
		  <b>Name:</b>
		  <%= @location.name %>
		</p>


		<%= link_to 'Edit', edit_location_path(@location) %> |
		<%= link_to 'Back', locations_path %>
	</div>
</div>

app/views/shared/_bar_left.html.erb
<div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
  <div class="sidebar-nav">

    <% if current_user.roles == 'guest' %>
      <div class="list-group">
        <a href="#" class="list-group-item active ">
          <span class="glyphicon glyphicon-align-justify"></span>
          <span class='badge pull-right'>
            <%= @loc_pub.count %>
          </span> Channel Location CCTV
        </a>
        <% @loc_pub.each do |loc| %>
        <%= link_to "<span class='glyphicon glyphicon-play-circle'></span> #{loc.name}".html_safe, channel_pub_path(loc.id),{class: "list-group-item"} %> 
        <% end %>
      </div>
    <% elsif %>
      <div class="list-group">
        <a href="#" class="list-group-item active ">
          <span class="glyphicon glyphicon-user"></span> Manage User
        </a>
        <%= link_to "Create User", new_user_path, class: "list-group-item" %>
        <%= link_to "List Users", users_path, class: "list-group-item" %>
        <a href="#" class="list-group-item active ">
          <span class="glyphicon glyphicon-map-marker"></span> Manage Location
        </a>
        <%= link_to "Create Location", new_location_path, class: "list-group-item" %>
        <%= link_to "List Location", locations_path, class: "list-group-item" %>
        <a href="#" class="list-group-item active ">
          <span class="glyphicon glyphicon-record"></span> Manage CCTV
        </a>
        <%= link_to "Create Channel", new_channel_path, class: "list-group-item" %>
        <%= link_to "List Channel", channels_path, class: "list-group-item" %>
      </div>
    <% end %>

  </div><!--/.well -->
</div><!--/span-->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "<span class='glyphicon glyphicon-record'></span> 
        CCTV Project 2013".html_safe, root_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse" style="height: 1px;">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.roles == 'guest' %>
          <li>
            <%= link_to "<span class='glyphicon glyphicon-star-empty'></span> Favorite Channel".html_safe, my_favorite_path %>
          </li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"></span> Account</a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Change Profile', edit_user_path(current_user.id) %></li>
            <li class="divider"></li>
            <li><%= link_to "SignOut", destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>
<!-- /.navbar -->

app/views/users/_form.html.erb
<%= f.fields_for(:profile_attributes, user_profile) do |profile| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-block alert-danger fade in ">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Warning!</strong> <%= pluralize(@user.errors.count, "error") %>
        <% @user.errors.full_messages.each do |msg| %>
        <diV>
          <%= msg %>
        </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <%= profile.hidden_field :id %>
  <% if current_user.roles == 'admin' %>
    <%= f.hidden_field :roles, value: 'guest'%>
  <% end %>
  <div class="col-lg-6">
    <div class="input-group">
      <div>First Name</div>
      <%= profile.text_field :first_name, class: 'form-control',placeholder:'First Name' %>
    </div>
    <div class="input-group">
      <div>Last Name</div>
      <%= profile.text_field :last_name, class: 'form-control',placeholder:'Last Name' %>
    </div>
    <div class="input-group">
      <div>Email</div>
      <%= f.text_field :email, class: 'form-control',placeholder:'Email' %>
    </div>
    <div class="input-group">
      <div>Password</div>
      <%= f.password_field :password, class: 'form-control',placeholder:'Password' %>
    </div>
    <div class="input-group">
      <div>Password Confirmation</div>
      <%= f.password_field :password_confirmation, class: 'form-control',placeholder:'Password Confirmation' %>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="input-group">
      <div>Mobile Phone</div>
      <%= profile.text_field :mobile_phone, class: 'form-control',placeholder:'Mobile Phone' %>
    </div>
    <div class="input-group">
      <div>Phone</div>
      <%= profile.text_field :phone, class: 'form-control',placeholder:'Phone' %>
    </div>
    <div class="block"></div>
    <button type="button" class="btn btn-default">
      <%= link_to "Close", users_path %>
    </button>
    <button type="submit" class="btn btn-primary">Save As</button>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row">    
  <div class="bs-example">
    <div class="panel-heading">Change User</div><br>
    <%= form_for(:user, url: user_path(@user.id), method: "put", html: {class: "form-horizontal margin-none"}) do |f| %>
      <%= render partial:"form", locals: {f: f, user_profile: @user.profile} %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">   
  <div class="bs-example">
    <div class="panel-heading">List Users</div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Full Name</th>
          <th>Email</th>
          <th width="15%">Action</th>
        </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
        <tr>
          <td></td>
          <td><%= user.profile.first_name %> <%= user.profile.last_name %></td>
          <td><%= user.email %></td>
          <td>
            <%= link_to "<span class='glyphicon glyphicon-wrench'>".html_safe, edit_user_path(user) %> 
            <%= link_to "<span class='glyphicon glyphicon-trash'>".html_safe, user, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%= link_to "<span class='glyphicon glyphicon-eye-open'>".html_safe, user %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div>
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">    
  <div class="bs-example">
    <div class="panel-heading">Create User</div><br>
    <%= form_for(:user, url: users_path, method: "post", html: {class: "form-horizontal"}) do |f| %>
      <%= render partial:"form", locals: {f: f, user_profile: {}} %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="bs-example">
		<% if notice.present? %>
			<div class="alert alert-warning fade in">
		    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
		    <%= notice %>
		  </div>
	  <% end %>
		<table class="table table-striped">
      <thead>
        <tr>
          <th width="20%">First Name</th>
          <th><%= @user.profile.first_name %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><b>Last Name</b></td>
          <td><%= @user.profile.last_name %></td>
        </tr>
        <tr>
          <td><b>Email</b></td>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td><b>Mobile Phone</b></td>
          <td><%= @user.profile.mobile_phone %></td>
        </tr>
        <tr>
          <td><b>Phone</b></td>
          <td><%= @user.profile.phone %></td>
        </tr>
      </tbody>
    </table>

		<%= link_to 'Edit', edit_user_path(@user) %> |
		<%= link_to 'Back', users_path %>
	</div>
</div>